### PR TITLE
sql/ast: Resolve return values from functions

### LINKED ISSUE #199: SELECT from FUNCTION return
```sql
CREATE FUNCTION foo() RETURNS bool AS $$ SELECT true $$ LANGUAGE sql;

-- name: FromFoo :one
SELECT * FROM foo();
```

Fails with the error `empty edit contents`

### PR DESCRIPTION
**Pull request by kylecarbs**
Closes #199.

Thanks to @warent for the prior art in #846!

Feedback is very welcomed. Not certain I'm doing this the best way...

### CODE REVIEW

**Comment by cmoog** [comment]
cc @coadler

**Review by kyleconroy — CHANGES_REQUESTED** [review]
The changes look great. Can you add a end-to-end test for this feature? There are a bunch of examples in the `internal/endtoend/testdata` folder. If you could add it for both MySQL and PostgreSQL that would be even better.

**Comment by kylecarbs** [comment]
@kyleconroy MySQL returns single-types from functions, so this isn't really applicable. However, I did add a PostgreSQL test. 🥳

**Comment by kylecarbs** [comment]
@kyleconroy anything else needed for this to merge?

**Review by kyleconroy — APPROVED** [review]

**Comment by kyleconroy** [comment]
Nope!

**Pull request merged**
