### PR TITLE
MySQL support

### PR DESCRIPTION
**Pull request by kyleconroy**
```json
{
  "version": "1",
  "packages": [
    {
      "name": "bar",
      "engine": "mysql",
      "path": "internal/bar",
      "queries": "./sql/query/",
      "schema": "./sql/schema/"
    }
  ]
}
```

TODO:
- [x] Support directories when parsing schema / queries
- [x] Successfully generate code for the [booktest](https://github.com/kyleconroy/sqlc-examples/tree/master/booktest) package
- [ ] Support comments that start with `-- `
- [x] Pick a better field name than `database`

### CODE REVIEW

**Comment by kyleconroy** [comment]
@cmoog I think I'm ready to merge this in. Mind taking a look at my new commits?

**Comment by cmoog** [comment]
@kyleconroy Nice. Your new commits look great. 
One missing feature I forgot to mention is the ability for it to recognize repeat response types. At the moment it will always generate a new struct for each query response. I'm working on adding the feature now, but I suppose we could merge before the change is ready.

**Comment by kyleconroy** [comment]
> One missing feature I forgot to mention is the ability for it to recognize repeat response types.

Yeah, I think that's fine to add later. MySQL support will be marked as experimental

**Comment by kyleconroy** [comment]
Partial fix for #150

**Pull request merged**
