### PR TITLE
Support for nullable fields in joins

### PR DESCRIPTION
**Pull request by jwilner**
- Builds on top of https://github.com/kyleconroy/sqlc/pull/733
- Properly detects left, right, full joins
- Uses proper enum ordering

### CODE REVIEW

**Comment by jwilner** [comment]
@kyleconroy can we please enable CI for this PR? This issue is a major blocker for adoption for at least some of us.

**Comment by kyleconroy** [comment]
@jwilner CI has been enabled. I really hate that GitHub turned off actions for first time contributors.

**Comment by kyleconroy** [comment]
Fixes #374
Fixes #604

**Review by kyleconroy — APPROVED** [review]
Looks great! Thanks for getting this over the finish line. Can you merge in main? Once the tests pass again I'll merge.

**Comment by jwilner** [comment]
Thanks @kyleconroy! Merged in main. 

RE blocking CI for first time contributors, it kind of makes sense to me -- like a month ago I saw some malicious GH accounts open up thousands of PRs on https://github.com/golangci/golangci-lint to mine crypto with the CI. I assume blocking the CI is intended to deter that!

**Comment by johanbrandhorst** [comment]
This is awesome, can't wait for the next release, great work!

**Comment by fr3fou** [comment]
When is the next release getting published?

**Comment by ScottyFillups** [comment]
Super excited for the next release! Thanks @jwilner and @kyleconroy for all your hard work :smile:

**Pull request merged**
