### PR TITLE
Feat/nullable enums

### PR DESCRIPTION
**Pull request by sbres**
With this PR now custom Enums have a nullable structure like all the sql.NullXXXX

The Null structure is generated for every Enum.
When enums are present on the model we import `database/sql/driver`
The database type matching is a little bit dirty I think something better can be done, let me know if you have an idea.

Also, how should I go about creating tests for this?

### CODE REVIEW

**Review by kyleconroy — DISMISSED** [review]
To test this, we need to add or update the existing test queries in `internal/endtoend`. We should write a SELECT, INSERT, UPDATE, and DELETE query for both MySQL and PostgreSQL to verify that the null types are used correctly.

**Comment by sbres** [comment]
I'll try to get those examples sorted out 👍

**Comment by sbres** [comment]
I've added the examples on sqlc/internal/endtoend/testdata/enum

**Comment by danielbprice** [comment]
Please excuse the unsolicited comment but: Thanks for doing this!  I hit exactly this problem tonight when testing the new sqlc.narg() functionality with an enum type.  I pulled your branch, built it, and I can confirm that your fix seemed to cleanly solve this problem for my query, which looks like this:

```
 SELECT *
 FROM sessions
WHERE
  sqlc.narg('Status')::session_status IS NULL OR status = sqlc.narg('Status')
...
```

I really appreciate this.

**Comment by sbres** [comment]
@danielbprice Thanks for your comment, I got scared that there was a bug on the first two sentences hahaha.

@kyleconroy Do you think you can have a look at this PR? The changes you requested have been done :)

**Comment by tinyzimmer** [comment]
Also recently ran into this issue and looking forward to this PR. If there is anything I can do to contribute (code-wise or testing) let me know.

**Comment by tinyzimmer** [comment]
I'll fork ya and see if I have any luck

**Comment by tinyzimmer** [comment]
@sbres I've fixed the failing test on a PR into your branch, but I'm unsure if that's all the issue was or not.

**Comment by tinyzimmer** [comment]
@sbres Have you a chance to look at my PR. I'm still not sure if it's sufficient, but would love to see this get merged.

**Comment by sbres** [comment]
@tinyzimmer I've merged it the PR on the forked repo did not have the CI/CD let's see if it gets resolved

**Comment by tinyzimmer** [comment]
@kyleconroy curious if you'll have time in the future to re-review. Assuming the test fixes are appropriate along with everything else.

**Comment by sbres** [comment]
@kyleconroy Can you please have a look at this, the requested changes have been done in April.
I'm coming close to delivering a project at work and I can't say "just use my forked branch".

**Comment by kyleconroy** [comment]
@sbres Currently traveling, but will have some time to review in the next few days

**Review by kyleconroy — APPROVED** [review]

**Review by kyleconroy — APPROVED** [review]

**Comment by kyleconroy** [comment]
@sbres Sorry this took so long to review, but I'm quite happy where it ended up.

**Pull request merged**
