### PR TITLE
docs: add documentation and examples for `sqlc.narg`

### PR DESCRIPTION
**Pull request by skabbes**
To complete the `sqlc.narg` feature defined here: https://github.com/kyleconroy/sqlc/pull/1536

Feel free to edit / make your own my tone / wording.

### CODE REVIEW

**Comment by skabbes** [comment]
@kyleconroy can you pay special attention to this:
https://github.com/kyleconroy/sqlc/pull/1579/commits/b9efe90f53b8d937804a676429f986811caefbd3

I am not sure if it was the right thing to do, but it seemed completely unused (or at least unneeded)

Could you also review the recommitting of the python and kotlin examples. I tried to fix a kotlin issue, but I have no idea what the correct kotlin should be.  Maybe @mightyguava is around to advise?

**Comment by skabbes** [comment]
Given the build issues I am having, I isolated the documentation only (no examples) [here](https://github.com/kyleconroy/sqlc/pull/1580)

**Review by kyleconroy — COMMENTED** [review]
I also don't know Kotlin super well. Will take me quite a bit to review this one.

**Comment by skabbes** [comment]
I think we can likely just close this then.  Anyone trying to use `sqlc.narg` (or `sqlc.arg` for that matter) + kotlin will have issues, but at that point we'll have a Kotlin expert to weigh in and advise.

**Comment by mightyguava** [comment]
Sorry, I didn’t quite end up getting adoption this on my side either. 😞

**Pull request closed without merging**
