### PR TITLE
Return an error from Schema.Add when the table spec is nil

### PR DESCRIPTION
**Pull request by alecbz**
Ran into this error when trying to process a SQL file introducing a view, and
it was hard to chase down.

---
This change is [Reviewable](https://reviewable.io/reviews/kyleconroy/sqlc/608)

### CODE REVIEW

**Comment by alecbz** [comment]
@kyleconroy

**Comment by kyleconroy** [comment]
The MySQL package is deprecated, but I'm happy to fix small bugs like this since the new MySQL support is blocked on a few upstream issues.

**Comment by alecbz** [comment]
> The MySQL package is deprecated, but I'm happy to fix small bugs like this since the new MySQL support is blocked on a few upstream issues.

Ah got it.

Is there a way to enable new MySQL support instead, or is not ready to even try out yet?

**Comment by alecbz** [comment]
@kyleconroy Also, anything contributors can do to help push the new MySQL stuff along? Is there a list of issues/tasks somewhere? Would love to help if possible!

**Comment by kyleconroy** [comment]
If you're interested in helping out with the new MySQL support, take a look at my recent pull requests

- https://github.com/kyleconroy/sqlc/pull/626
- https://github.com/kyleconroy/sqlc/pull/625
- https://github.com/kyleconroy/sqlc/pull/624
- https://github.com/kyleconroy/sqlc/pull/623
- https://github.com/kyleconroy/sqlc/pull/622
- https://github.com/kyleconroy/sqlc/pull/621
- https://github.com/kyleconroy/sqlc/pull/620
- https://github.com/kyleconroy/sqlc/pull/619

They all follow the same pattern. Take an existing test for PostgreSQL and attempt to port it to MySQL. Update `convert.go` with the necessary AST translation to get the tests to pass.

**Comment by alecbz** [comment]
Also @kyleconroy :

> Is there a way to enable new MySQL support instead, or is not ready to even try out yet?

We're trying to get started with sqlc for an existing codebase, would you recommend going with the existing deprecated support or trying out the new stuff?

**Comment by kyleconroy** [comment]
Please try the new stuff first, even though I'm sure you'll run into bugs. You'll need to use a [tip release](https://github.com/kyleconroy/sqlc#tip-releases). Instead of `mysql`, set your engine value to `_dolphin`.

**Pull request merged**
