### PR TITLE
Add support for emitting pointer types for nullable columns

### PR DESCRIPTION
**Pull request by nickbruun**
pgx/v4 supports passing and scanning into pointer types for nullable columns instead of using the standard library `Null<Type>` representation, which is super handy if you wind up interfacing a lot with, say, generated Protocol Buffer files using the proto3 `optional` flag.

This PR adds a new configuration option `emit_pointers_for_null_types`, which, as per the documentation line added:

> If true and `sql_package` is set to `pgx/v4`, generated types for nullable types are emitted as pointers (ie. `*string`) instead of `database/sql` null types (ie. `NullString`). Defaults to `false`.

This change would be a significant quality-of-life improvement for me, but I obviously don't know if it generally fits with the philosophy of sqlc, so consider this a suggestion and please feel free to provide any feedback (including, but not limited to bike-shedding of the choice of name for the configuration parameter, if we see this feature fit for sqlc.)

Lastly, thanks all for building this tool. It's genuinely saved me tons of hours writing the same pesky boiler plate with limited guarantees.

### CODE REVIEW

**Comment by topheruk** [comment]
how can I try this out? I have been looking at the alternative which is to manually override but that is pretty tedious. would like to try this out just don't know how to include it.

**Comment by mvrhov** [comment]
This was implemented before (named a bit differently), but it has been removed. #814 has a list of needed overrides. Which is a bit tedious to copy around I'd say.

**Comment by topheruk** [comment]
@mvrhov so is it just recommend to add them manually then I'm guessing?

Thanks for this list as it does help.

**Comment by mvrhov** [comment]
For now I guess. I do like this PR because then I don't have to copy a bunch of lines into each project.

**Comment by nickbruun** [comment]
Certainly avoiding having to copying a bunch of lines around would be a huge improvement. Any chance this could be considered for a merge, despite prior history, @mvrhov?

**Comment by mvrhov** [comment]
@nickbruun It's not my decision on what's getting merged.

**Comment by nickbruun** [comment]
@mvrhov I understand – mostly just wondering what historical context you can provide since it sounds like this was tried before?

**Comment by kyleconroy** [comment]
@nickbruun Sorry that I'm just getting around to getting this reviewed. I know it's been months since it was opened.

I'm onboard with this change and would like to get it merged for the pgx/v5 release https://github.com/kyleconroy/sqlc/issues/1823

**Review by kyleconroy — COMMENTED** [review]
How should this work in conjunction with the new [pgtype](https://pkg.go.dev/github.com/jackc/pgx/v5@v5.0.0-beta.3/pgtype) package? I think we should only return pointers to non-pgtype types. Thoughts?

**Comment by nickbruun** [comment]
Let me review the changes from pgx/v5 and I'm happy to update in accordance :)

**Comment by brlala** [comment]
would be good to have this feature in v5

**Comment by JamesArthurHolland** [comment]
Is this going to be merged soon? I'm using sqlc, gqlgen and gqlgenc, getting an error about String is incompatible with database/sql.NullString and I'd much rather use the pointers for null types.

**Comment by nickbruun** [comment]
Oh wow, I totally got behind on developing a coherent view on pgx/v5. Thanks for merging this!

**Pull request merged**
