### PR TITLE
Update parse.go

### PR DESCRIPTION
**Pull request by bodison**
fixes https://github.com/kyleconroy/sqlc/issues/1007

### CODE REVIEW

**Comment by bodison** [comment]
Thanks for reviewing this. I'll add a test tomorrow :)

**Comment by bodison** [comment]
I added tests and I added the BOM removal to a few more locations.

But I'm not happy with the test coverage.

**Comment by bodison** [comment]
I'm worried that the three tests I added seem to only test one of these places:
internal/compiler/compile.go:108

It does not test:
internal/compiler/compile.go:71
internal/engine/dolphin/parse.go:60
internal/engine/postgresql/parse.go:162
internal/engine/sqlite/parse.go:51

Am I mistaken?

**Comment by kyleconroy** [comment]
@bodison You're right that we need to solve this in a more general way. I'm going to close this PR and update the linked issue with better description of the issue and a few possible implementations.

**Comment by bodison** [comment]
@kyleconroy I wouldn't say we have to solve it in a more general way. IMO removing the BOM is a very niche issue and can be done whenever you open a file to read.

The only thing I do not like/understand is the test coverage of the four files I edited. But I'm afraid I do not have a contribution to improve this, since I barely know the code base.

The original issue would be solved with this PR, the insufficient test coverage should be a different issue IMO.

<3

**Pull request closed without merging**
