### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by adesokanayo**
Updating macOS installation from ```brew install sqlc``` to ``` brew install kyleconroy/sqlc/sqlc```

### CODE REVIEW

**Comment by kyleconroy** [comment]
sqlc is an officially supported Brew formula and does not need kyleconroy/sqlc prefx. Are you seeing issues with `brew install sqlc`?

**Comment by adesokanayo** [comment]
Thanks  @kyleconroy , I could not use brew install sqlc and got error, perhaps, it was just something peculiar with my version of brew.

**Comment by kyleconroy** [comment]
Can you post the error you got when trying to install via brew?

**Comment by adesokanayo** [comment]
Screen Shot 2021-08-15 at 8 36 39 AM

I got the above error  when i tried installing earlier , but it  works now  with ```brew install sqlc```

**Pull request closed without merging**
