### PR TITLE
feat: ignore seeder sql file

### PR DESCRIPTION
**Pull request by dongyu**

### CODE REVIEW

**Comment by kyleconroy** [comment]
Could you provide a link to the tool that uses these files?

**Comment by dongyu** [comment]
Insert seed data using [sql-migrate](https://github.com/rubenv/sql-migrate)

**Comment by kyleconroy** [comment]
@dongyu looking over the docs for sql-migrate, I can't find any reference to `.seed.sql` or `.seeder.sql` files. Do you know where support for these files lives?

**Comment by kyleconroy** [comment]
I'm going to close this for the time being. Please feel free to respond with a link to the sql-migrate documentation that mentions seed SQL files.

**Pull request closed without merging**
