### PR TITLE
Refactor to Package Catalog to Improve Readability

### PR DESCRIPTION
**Pull request by jakoguta**
This PR moves code around files in the package catalog to make it self documenting. It also adds comments to help better explain and document the code. This will make it more easy for new contributors to quickly understand the code and its implementation. There are also tests added to the package to ensure that as the code base evolves breaking changes are caught early in the unit tests.

NB: This refactor has only focused on tests and documentation.

### CODE REVIEW

**Comment by jakoguta** [comment]
This is well noted. I will move what is not already covered with end-to-end testing there.

**Comment by jakoguta** [comment]
I have removed the unit tests in favor of endtoend tests

**Comment by kyleconroy** [comment]
Did you end up writing new endtoend tests? There aren't any in the changes.

**Review by kyleconroy — APPROVED** [review]
Looks good to me

**Comment by jakoguta** [comment]
> Did you end up writing new endtoend tests? There aren't any in the changes.

I am still working on what I want to add to the endtoend test.

**Pull request merged**
