### PR TITLE
Python query param limit

### PR DESCRIPTION
**Pull request by danicc097**
Related to #1498 , but gives support for a `query_parameter_limit` in Python codegen, very much desirable for my use case with FastAPI. 

Initially I wanted to also include Go, but I've failed miserably since all Go code generation uses a single param and don't know about the best way to proceed that requires minimal changes

### CODE REVIEW

**Review by kyleconroy — COMMENTED** [review]
I updated the issue with a bit of different behavior

> We can set the value to a pointer in the configuration YAML / JSON so that zero is a valid option. Anything less than zero should be an error.

**Comment by kyleconroy** [comment]
@danicc097 Sorry for taking forever on this code review. I can promise a quick review if you're able to fix the merge conflicts. If not, I totally understand.

**Comment by danicc097** [comment]
@kyleconroy I noticed Python currently has a default limit of 4, the change to 1 would be breaking. Want to keep it anyway for consistency?

**Comment by kyleconroy** [comment]
We should keep the default the same, even if it isn't the same as Go's

**Pull request merged**
